name: PHP CodeSniffer

on:
    workflow_call:

jobs:
  lint:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'
        ini-values: 'memory_limit=1G'
        coverage: none
        tools: cs2pr

    - name: Install Composer dependencies
      uses: "ramsey/composer-install@v3"
      with:
        # Bust the cache at least once a month - output format: YYYY-MM.
        custom-cache-suffix: $(date -u "+%Y-%m")

    - name: Run PHPCS checks
      id: phpcs
      run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

    - name: Show PHPCS results in PR
      if: ${{ always() && steps.phpcs.outcome == 'failure' }}
      run: cs2pr ./phpcs-report.xml